### ISSUE TITLE
what can i do something for get the noticications queue?

### ISSUE THREAD

**Issue by YafXe** [f3oall/vue-awesome-notifications#1]
rt.. because some action can be  cause this notifications frequently, so i need to clear the queue, what can i get the loop queue?  my en is so badly ...  sorry   ..

**Comment by f3oall** [comment]
Well, there is no way to do this by library methods.  If you want to remove all notifications at once, the only option is to manipulate DOM directly. Just choose notifications container and remove all its child.

Hope it helps. If i didn't understand you, feel free to clarify what you want.

**Comment by YafXe** [comment]
ok,,,thankyouverymuch, i know what should i do... thankyou verymuch again..

**Comment by f3oall** [comment]
You are welcome
