### ISSUE TITLE
style not working ?

### ISSUE THREAD

**Issue by matamune94** [f3oall/vue-awesome-notifications#11]
pls check

**Comment by diakonovm** [comment]
@matamune94 If you are using Nuxt, then simply import the file within `nuxt.config.js`.

```
  /*
  ** Global CSS
  */
  css: [
    'vue-awesome-notifications/dist/styles/style.css'
  ]
```

**Comment by Nickfrm** [comment]
Vue integration section in docs was updated. CSS import guide was added: https://f3oall.github.io/awesome-notifications/docs/integrations/vue
