### ISSUE TITLE
notification not showing 

### ISSUE THREAD

**Issue by captainamiedi** [f3oall/vue-awesome-notifications#12]
here is what i did
on main.ts file 
`import VueAWN from "vue-awesome-notifications";`

`let options = {
  position: "top-right"
}`
`Vue.use(VueAWN, options);`

on my component file
`this.$awn.info('file number is required')`

package json `"vue-awesome-notifications": "^3.0.3",`

But i didnt see any notification. 
maybe i'm not doing something right.
I'm using it on VUE

**Comment by Nickfrm** [comment]
Hi,
there's not enough info to provide you any help, can you please share your whole component in codepen for example.

**Comment by Nickfrm** [comment]
Also, please check this updated docs: https://f3oall.github.io/awesome-notifications/docs/integrations/vue
Here was added a CSS import guide, probably you forget to do this.

**Comment by captainamiedi** [comment]
thanks Nickfrm. it now working
