### ISSUE TITLE
sytle.css not incluced anymore, no backward compatibility 

### ISSUE THREAD

**Issue by maleta** [f3oall/vue-awesome-notifications#2]
As said in title, my asset pipeline is not compiling anymore because you removed style.css file in version 2.2.6. Because of that you should move this code to version 3.0.0(marking it as not backward compatible with 2.*) or upload again style.css file.

Thanks

**Comment by f3oall** [comment]
Hi,

I'm sorry for this issue it was just my mistake. I fixed it in 2.2.9

Thank you for your feedback.
