### ISSUE TITLE
AWN for Vue 3

### ISSUE THREAD

**Issue by MehdiMamas** [f3oall/vue-awesome-notifications#21]
```
import { createApp } from "vue"
import App from './App.vue'
import VueAWN from "vue-awesome-notifications"
var app = createApp(App)
app.use(VueAWN).use(VueSweetalert2).use(store).use(router).component('faicon', FontAwesomeIcon).mount('#app')
```
adding it this way gives me this error:
![image](https://user-images.githubusercontent.com/46635765/154061448-f707a552-48d6-4400-b706-51b3d989b6d5.png)

**Comment by cjonstrup** [comment]
https://github.com/f3oall/vue-awesome-notifications/issues/22#issuecomment-1184267010
