### ISSUE TITLE
How to apply notifier.asyncBlock(asyncFunc(), ) 

### ISSUE THREAD

**Issue by allaghi** [f3oall/vue-awesome-notifications#5]
Hi, 
Have a nice day,
I am wondering how to apply notifier.asyncBlock with vue js when I want to submit data.
I am using axios with vue js and as backend I am using laravel . I don't have any issue with posting data.
but what I really want is how to apply notifier.asyncBlock with my function which is used to post data into
database.
Thanks In Advance.
Saad Allaghi

**Comment by f3oall** [comment]
Hey, you should just send any JS promise as first parameter to the asyncBlock function. Then untill Promise is resolved or rejected, the block popup will be shown. Read docs to learn more about this function
