### ISSUE TITLE
Notifications don't disappear anymore

### ISSUE THREAD

**Issue by syc-pad** [f3oall/vue-awesome-notifications#6]
Suddenly, the notifications don't disappear automatically at the end of the time set in the options.
I didn't change anything.
User has to click each time on the notification to make it disappear.

Version of the lib : 2.2.9

**Comment by f3oall** [comment]
I can't help you because you didn't provide any related info about your issue. You can try to use 3.0.0 version, it works as expected for sure.

Personally, I believe that described issue in 2.2.9 is on your side.
