### ISSUE TITLE
Promises not working?

### ISSUE THREAD

**Issue by SeoRoman** [f3oall/vue-awesome-notifications#8]
to clean up the same code a bit... I changed it to the following:

`
methods: {		

		save () 
		{
			this.$awn.asyncBlock(
				this.$store.dispatch('Assets/CREATE', this.form.data()),
				'SUCCESS',
				'ERROR',
				'Saving Asset...'
			)
		}

	}
`

and...

CREATE({commit}, data)
		{
			return new Promise((resolve, reject) => {
				axios.post('/api/v1/assets/assets', data)
					.then(response => {
						resolve(response)
					})
					.catch(err => {
						reject(err.response)
					})
			})
		}

Issue is just before the 'ERROR' appears, I get Uncaught Promise exception... I have used console.log()'s to determine that it happens just before the popup appears, and the console.log() displays right afterwards... not entirely sure what's going on here...

**Comment by SeoRoman** [comment]
Sorry for the horrible formatting... I used the <> code tool but that didn't work :D

**Comment by SeoRoman** [comment]
I have also removed the entire Form Class and went straight to the VueX store, but the same thing happens... just before the asyncBlock() catches the error, I get an Uncaught Error exception

**Comment by SeoRoman** [comment]
to clean up the same code a bit... I changed it to the following:

methods: {		

		save () 
		{
			this.$awn.asyncBlock(
				this.$store.dispatch('Assets/CREATE', this.form.data()),
				'SUCCESS',
				'ERROR',
				'Saving Asset...'
			)
		}

	},

and...

CREATE({commit}, data)
	    {
	    	return new Promise((resolve, reject) => {
	    		axios.post('/api/v1/assets', data)
	    			.then((response) => {	    		    			
	    				resolve(response)
	    			})
	    			.catch((err) => {
	    				reject(err.response) // tried reject(err) too
	    			})
	    	})
	    }

**Comment by SeoRoman** [comment]
Actually if you check out the demo's ... this happens there too :D 

https://f3oall.github.io/awesome-notifications/docs/popups/async-block

I thought I was doing something wrong, but if you watch the console window when you click some of the examples, it does the same thing...

**Comment by f3oall** [comment]
Thanks for your feedback. It's probably just a console error, which doesn't affect your app work, but I will try to remove it as soon as possible.

This issue is related to the `awesome-notifications` library, so next time create the issue in proper project please.

**Comment by SeoRoman** [comment]
gotcha will do, sorry, I only use this package on vue, so just assumed :D

**Comment by Nickfrm** [comment]
This issue was fixed in v3.0.5
